### ISSUE TITLE
OpenSSL 3.0 deprecation notice `ERR_load_BIO_strings`

### ISSUE THREAD

**Issue by wunderfeyd** [gateway-services/chipdna-winlin-client-cpp#18]
Hi,
when compiling the client against [OpenSSL 3.0.1](https://github.com/openssl/openssl/commit/b4e83ed7cd99c12d27e0e220c3afa1745a68f921) on Linux the compiler emits following warning:
```
../src/tcpipclient.cpp: In member function ‘bool ChipDnaClientLib::TcpIpClient::connectSSL(std::string, std::string)’:
../src/tcpipclient.cpp:81:37: warning: ‘int ERR_load_BIO_strings()’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   81 |                 ERR_load_BIO_strings();
      |                 ~~~~~~~~~~~~~~~~~~~~^~
In file included from ../../../../../../output/tmp/linux-x64/openssl/include/openssl/cryptoerr.h:17,
                 from ../../../../../../output/tmp/linux-x64/openssl/include/openssl/crypto.h:38,
                 from ../../../../../../output/tmp/linux-x64/openssl/include/openssl/bio.h:30,
                 from ../include/clientbase.h:22,
                 from ../include/tcpipclient.h:4,
                 from ../src/tcpipclient.cpp:1:
../../../../../../output/tmp/linux-x64/openssl/include/openssl/cryptoerr_legacy.h:31:27: note: declared here
   31 | OSSL_DEPRECATEDIN_3_0 int ERR_load_BIO_strings(void);
      |                           ^~~~~~~~~~~~~~~~~~~~
```

Build OpenSSL version:
```
$ ../bin/openssl version
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
```

According to the [README.md](https://github.com/gateway-services/chipdna-winlin-client-cpp/blob/master/README.md) OpenSSL with version 1.0.1 is a requirement. But it looks like 1.0.1 isn't supported anymore.

**Comment by njsws** [comment]
Hi wunderfeyd,

Thanks for your report. As it happens we are actively working on addressing this and an update will be released in the near future.

**Comment by mbsws** [comment]
Hi wunderfeyd,

We haven't forgotten about this issue but were unable to get it into the latest 3.06 release. We'll update here once we know when it will be resolved.

**Comment by wunderfeyd** [comment]
No problem. Thanks for sharing this information. :+1:

**Comment by mbsws** [comment]
Hi wunderfeyd,

We added support for OpenSSL 3.x.x in 3.07 Prime.

**Comment by wunderfeyd** [comment]
Thank you very much.

Have a nice weekend. :partying_face:
