### ISSUE TITLE
Library compatible with ChipDNA Server 3.12 Myrddin?

### ISSUE THREAD

**Issue by wunderfeyd** [gateway-services/chipdna-winlin-client-cpp#27]
I had the request to go directly to ChipDNA 3.12 because of newer devices used at site and for some sustainability. Is the master compatible with 3.12 or do you update this any time soon? (@mbsws @gateway-services).

**Comment by cmsws** [comment]
Hi, thank you for your notification.

We are intending to update the clients to 3.12 Myrddin shortly, although I am not able to provide a date just at the moment.

That release will include changes to the Makefiles; the changes to the source files are limited to the version & release name in `libraryversion.cpp` plus the source code alterations from https://github.com/gateway-services/chipdna-winlin-client-cpp/pull/17

**Comment by cmsws** [comment]
Hi wunderfeyd,

The clients have now been updated to 3.12 Myrddin.

**Comment by wunderfeyd** [comment]
Thank you very much. :+1:
