### ISSUE TITLE
Linux (arm) Makefile referenced sources are not present

### ISSUE THREAD

**Issue by wunderfeyd** [gateway-services/chipdna-winlin-client-cpp#5]
Build fails as soon it tries to fetch `src/merchantdata.cpp` or `src/merchant.cpp`.

Either these files are missing in the repository or the references are invalid.

**Comment by mbsws** [comment]
This is resolved in 2.15 Athena.

**Comment by wunderfeyd** [comment]
Thank you. :+1:
